"""Regressions for semantic generated-header detection and cache provenance."""

from __future__ import annotations

from collections.abc import Iterable, Iterator, Mapping
from pathlib import Path

import pytest

import _04_Nucleo_Operativo.code_detection as code_detection
import _04_Nucleo_Operativo.code_route as code_route_module
from neocortex.deduplication import FileSnapshot
from _04_Nucleo_Operativo.code_contracts import (
    ArtifactKind,
    CodeRouteConfig,
)
from _04_Nucleo_Operativo.code_detection import (
    DETECTOR_VERSION,
    classify_artifact,
)
from _04_Nucleo_Operativo.code_route import CodeRoute


# region [01] Generated-header classification


@pytest.mark.parametrize(  # type: ignore[untyped-decorator]
    ("path", "text", "style"),
    (
        (
            Path("src/client.py"),
            "# Copyright 2026\n# This file is auto-generated. Do not edit.\nvalue = 1\n",
            "hash",
        ),
        (
            Path("src/client.ts"),
            "// Code generated by schema-tool. DO NOT EDIT.\nexport const value = 1;\n",
            "slash",
        ),
        (
            Path("src/client.go"),
            "// WARNING: This file is machine generated.\npackage client\n",
            "slash",
        ),
        (
            Path("src/client.cs"),
            "/*\n * <auto-generated />\n */\ninternal sealed class Client {}\n",
            "c-block",
        ),
        (
            Path("src/client.xml"),
            '<?xml version="1.0"?>\n<!-- This file was automatically generated. -->\n<client />\n',
            "xml-block",
        ),
        (
            Path("src/client.ps1"),
            "<#\n@generated\n#>\nWrite-Output 'ready'\n",
            "powershell-block",
        ),
    ),
)
def test_semantic_header_comments_mark_generated_artifacts(
    path: Path,
    text: str,
    style: str,
) -> None:
    classification = classify_artifact(path, text)

    assert classification.artifact_kind is ArtifactKind.GENERATED
    assert classification.generated is True
    assert "header:generated-marker" in classification.evidence
    assert f"detector:{DETECTOR_VERSION}" in classification.evidence
    assert any(
        item.startswith(f"header:generated-marker:{style}:line-")
        for item in classification.evidence
    )


@pytest.mark.parametrize(  # type: ignore[untyped-decorator]
    ("path", "text"),
    (
        (
            Path("src/rules.py"),
            "import re\nMARKER = re.compile(r'do not edit|generated file|@generated')\n",
        ),
        (
            Path("src/rules.py"),
            '"""Generated file markers recognized by this detector."""\nvalue = 1\n',
        ),
        (
            Path("src/rules.py"),
            "# Detector recognizes generated file declarations.\nvalue = 1\n",
        ),
        (
            Path("src/rules.py"),
            "value = 1\n# This file is generated.\n",
        ),
        (
            Path("src/rules.ts"),
            'const marker = "// generated file";\nexport { marker };\n',
        ),
        (
            Path("src/rules.json"),
            '{"notice": "do not edit", "kind": "generated file"}\n',
        ),
    ),
)
def test_rule_literals_and_non_header_text_are_not_generated(
    path: Path,
    text: str,
) -> None:
    classification = classify_artifact(path, text)

    assert classification.artifact_kind is not ArtifactKind.GENERATED
    assert classification.generated is False
    assert "header:generated-marker" not in classification.evidence


def test_detector_does_not_classify_its_own_rule_literals_as_generated() -> None:
    module_file = code_detection.__file__
    assert module_file is not None
    detector_path = Path(module_file).resolve()

    classification = classify_artifact(
        detector_path,
        detector_path.read_text(encoding="utf-8"),
    )

    assert classification.artifact_kind is ArtifactKind.SOURCE
    assert classification.generated is False
    assert "header:generated-marker" not in classification.evidence


def test_generated_path_role_remains_supported_without_a_header() -> None:
    classification = classify_artifact(
        Path("src/build/client.py"),
        "value = 1\n",
    )

    assert classification.artifact_kind is ArtifactKind.GENERATED
    assert classification.generated is True
    assert "path:generated:build" in classification.evidence
    assert "header:generated-marker" not in classification.evidence


# endregion [01]


# region [02] Incremental cache signature


def _snapshot(path: Path) -> FileSnapshot:
    observed = path.stat()
    return FileSnapshot(
        str(path),
        observed.st_dev,
        observed.st_ino,
        observed.st_size,
        observed.st_mtime_ns,
        getattr(observed, "st_birthtime_ns", observed.st_ctime_ns),
    )


class _Inventory:
    def __init__(self, paths: Iterable[Path]):
        self.paths = tuple(paths)

    def snapshots(self, _scan_id: int) -> Iterator[FileSnapshot]:
        return iter(_snapshot(path) for path in self.paths)


class _FrameworkState:
    def begin_route_phase(
        self,
        _run_id: int,
        _route: str,
        _phase: str,
        *,
        source_run_id: int | None = None,
    ) -> None:
        del source_run_id

    def complete_route_phase(
        self,
        _run_id: int,
        _route: str,
        _phase: str,
        summary: Mapping[str, object] | None = None,
    ) -> None:
        assert summary is not None

    def fail_route_phase(
        self,
        _run_id: int,
        _route: str,
        _phase: str,
        _exc: BaseException,
    ) -> None:
        raise AssertionError("detector cache fixture route must not fail")


def test_detector_version_change_invalidates_the_incremental_cache(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    source = tmp_path / "client.py"
    source.write_text("def ready():\n    return True\n", encoding="utf-8")
    config = CodeRouteConfig(
        state_path=tmp_path / "state" / "code.sqlite3",
        dedup_path=tmp_path / "state" / "dedup.sqlite3",
    )
    inventory = _Inventory((source,))
    framework = _FrameworkState()

    first = CodeRoute(config, inventory, framework, 1, 1).run()
    cached = CodeRoute(config, inventory, framework, 2, 2).run()

    assert first.processed == 1
    assert cached.processed == 0
    assert cached.cache_hits == 1
    assert f"artifact-detector={DETECTOR_VERSION}" in first.processing_signature

    monkeypatch.setattr(
        code_route_module,
        "DETECTOR_VERSION",
        "code-artifact-detector-regression",
    )
    changed = CodeRoute(config, inventory, framework, 3, 3).run()

    assert changed.processing_signature != first.processing_signature
    assert changed.processed == 1
    assert changed.cache_hits == 0


# endregion [02]
