"""Conservative, byte/path-only origin signals for Code artifacts."""

from __future__ import annotations

from pathlib import Path

import pytest

from neocortex.code.code_contracts import ThirdPartyKind
from neocortex.code.ingestion.code_detection import (
    THIRD_PARTY_DETECTOR_VERSION,
    classify_code_provenance,
    classify_third_party_artifact,
)


def test_clean_code_requires_an_explicit_project_root_for_project_code(
    tmp_path: Path,
) -> None:
    source = tmp_path / "owned" / "src" / "main.py"

    scoped = classify_third_party_artifact(source, project_roots=(tmp_path / "owned",))
    unscoped = classify_third_party_artifact(source)

    assert scoped.kind is ThirdPartyKind.PROJECT_CODE
    assert scoped.confidence == 0.60
    assert scoped.cleanup_candidate is False
    assert scoped.is_third_party is False
    assert "scope:explicit-project-root" in scoped.evidence
    assert unscoped.kind is ThirdPartyKind.UNKNOWN
    assert "scope:ownership-unverified" in unscoped.evidence


@pytest.mark.parametrize(
    ("relative", "expected"),
    (
        ("project/node_modules/react/index.js", ThirdPartyKind.DEPENDENCY),
        ("project/.venv/lib/python3.14/site-packages/pkg/__init__.py", ThirdPartyKind.DEPENDENCY),
        ("project/vendor/openssl/ssl.c", ThirdPartyKind.VENDORED),
        ("project/third_party/zlib/z.c", ThirdPartyKind.VENDORED),
    ),
)
def test_dependency_and_vendored_paths_are_strong_origin_signals(
    relative: str,
    expected: ThirdPartyKind,
) -> None:
    classification = classify_third_party_artifact(relative)

    assert classification.kind is expected
    assert classification.is_third_party is True
    assert classification.cleanup_candidate is True
    assert classification.review_required is True
    assert classification.auto_trash_eligible is False
    assert any(item.startswith("path:") for item in classification.evidence)


def test_path_signals_are_composed_without_losing_binary_evidence() -> None:
    classification = classify_third_party_artifact(
        "project/node_modules/pkg/native.so",
        b"\x7fELF\x02\x01\x01\x00",
    )

    assert classification.kind is ThirdPartyKind.DEPENDENCY
    assert classification.is_binary is True
    assert ThirdPartyKind.BINARY in classification.signals
    assert "bytes:binary-magic:elf" in classification.evidence


@pytest.mark.parametrize(
    ("path", "text", "expected"),
    (
        ("project/build/app.js", "export const ready = true;\n", ThirdPartyKind.BUILD_ARTIFACT),
        ("project/generated/api.py", "VALUE = 1\n", ThirdPartyKind.GENERATED),
        (
            "project/src/client.py",
            "# Code generated by schema-tool. DO NOT EDIT.\nvalue = 1\n",
            ThirdPartyKind.GENERATED,
        ),
        ("project/.pytest_cache/lastfailed", "{}\n", ThirdPartyKind.CACHE),
    ),
)
def test_build_generated_and_cache_signals_are_separate_from_ownership(
    path: str,
    text: str,
    expected: ThirdPartyKind,
) -> None:
    classification = classify_third_party_artifact(
        path,
        text=text,
        project_roots=(Path("project"),),
    )

    assert classification.kind is expected
    assert classification.cleanup_candidate is True
    assert classification.is_third_party is False
    assert classification.auto_trash_eligible is False


def test_binary_status_and_extensions_are_advisory_not_ownership_proof() -> None:
    by_status = classify_third_party_artifact(
        "project/src/tool", analysis_status="binary", project_roots=(Path("project"),)
    )
    by_extension = classify_third_party_artifact(
        "project/src/tool.so", project_roots=(Path("project"),)
    )

    assert by_status.kind is ThirdPartyKind.BINARY
    assert by_extension.kind is ThirdPartyKind.BINARY
    assert by_status.is_third_party is False
    assert by_extension.is_third_party is False
    assert by_status.is_binary is by_extension.is_binary is True


def test_ambiguous_binary_probe_stays_below_default_cleanup_threshold() -> None:
    classification = classify_third_party_artifact(
        "project/src/tool", b"\x00\x01\x02binary-control"
    )

    assert classification.kind is ThirdPartyKind.BINARY
    assert classification.confidence == pytest.approx(0.70)


def test_project_root_name_does_not_become_a_dependency_signal() -> None:
    project = Path("vendor")
    classification = classify_third_party_artifact(
        project / "src" / "owned.py",
        project_roots=(project,),
    )

    assert classification.kind is ThirdPartyKind.PROJECT_CODE
    assert classification.cleanup_candidate is False


def test_manifest_and_similar_owned_names_do_not_trigger_dependency_rules() -> None:
    for path in (
        "project/src/dependencies.py",
        "project/src/build_notes.py",
        "project/package-lock.json",
    ):
        classification = classify_third_party_artifact(
            path,
            text="value = 'generated by a tool'\n",
            project_roots=(Path("project"),),
        )
        assert classification.kind is ThirdPartyKind.PROJECT_CODE
        assert classification.cleanup_candidate is False


def test_classifier_is_deterministic_and_alias_has_same_contract() -> None:
    path = Path("project/dist/vendor.min.js")
    payload = b"const bundle = true;\n"
    first = classify_third_party_artifact(path, payload)
    second = classify_code_provenance(path, payload)

    assert first == second
    assert first.evidence[0] == f"detector:{THIRD_PARTY_DETECTOR_VERSION}"
