"""Raw, import-free declarations for the Core capability registry."""

from __future__ import annotations

from typing import Final

CAPABILITY_SPEC_PAYLOADS: Final = (
    {
        "capability_id": "archive",
        "architecture_family_id": "neocortex.capabilities.formats",
        "logical_owner_id": "archive",
        "canonical_module_tree": "neocortex.capabilities.formats.archive",
        "modules": [
            {
                "role": "models",
                "canonical_module_id": "neocortex.capabilities.formats.archive.models",
                "public_symbols": ["ArchiveRouteSummary"],
                "warning_policy": "silent",
            },
            {
                "role": "route",
                "canonical_module_id": "neocortex.capabilities.formats.archive.route",
                "public_symbols": [
                    "ARCHIVE_MIME",
                    "ARCHIVE_ROUTE_VERSION",
                    "ArchiveRoute",
                    "ArchiveRouteConfig",
                    "ArchiveRouteSummary",
                ],
                "warning_policy": "silent",
            },
            {
                "role": "state",
                "canonical_module_id": "neocortex.capabilities.formats.archive.state",
                "public_symbols": [
                    "ARCHIVE_SCHEMA_VERSION",
                    "archive_database",
                    "archive_schema_contract",
                    "initialize_archive_state",
                ],
                "warning_policy": "silent",
            },
            {
                "role": "text_worker",
                "canonical_module_id": "neocortex.capabilities.formats.archive.text_worker",
                "public_symbols": ["main"],
                "warning_policy": "silent",
            },
        ],
        "route": {
            "route_name": "archive",
            "input_source": "route_candidates",
            "subject_match_kind": "exact_mime",
            "subject_value": "application/zip",
            "route_class": {
                "module_id": "neocortex.capabilities.formats.archive.route",
                "symbol_name": "ArchiveRoute",
            },
            "config_class": {
                "module_id": "neocortex.capabilities.formats.archive.route",
                "symbol_name": "ArchiveRouteConfig",
            },
            "summary_class": {
                "module_id": "neocortex.capabilities.formats.archive.route",
                "symbol_name": "ArchiveRouteSummary",
            },
            "version_symbol": {
                "module_id": "neocortex.capabilities.formats.archive.route",
                "symbol_name": "ARCHIVE_ROUTE_VERSION",
            },
        },
        "state": {
            "state_owner_id": "archive",
            "state_store_id": "sqlite:archive.sqlite3",
            "database_name": "archive.sqlite3",
            "knowledge_path_attribute": "archive",
            "expected_schema_version": 1,
            "knowledge_read_kind": "documents",
            "knowledge_capture_mode": "if_present",
            "state_module_id": "neocortex.capabilities.formats.archive.state",
            "schema_module_id": "neocortex.capabilities.formats.archive.state",
            "schema_version_symbol": {
                "module_id": "neocortex.capabilities.formats.archive.state",
                "symbol_name": "ARCHIVE_SCHEMA_VERSION",
            },
            "storage_engine": "sqlite",
        },
        "test_roots": [
            "tests/test_archive_cli.py",
            "tests/test_archive_route.py",
            "tests/test_archive_text_worker_unit.py",
            "tests/test_capability_registry.py",
            "tests/test_route_schema_contracts.py",
        ],
        "executable_module_ids": ["neocortex.capabilities.formats.archive.text_worker"],
    },
    {
        "capability_id": "audio",
        "architecture_family_id": "neocortex.capabilities.formats",
        "logical_owner_id": "audio",
        "canonical_module_tree": "neocortex.capabilities.formats.audio",
        "modules": [
            {
                "role": "models",
                "canonical_module_id": "neocortex.capabilities.formats.audio.models",
                "public_symbols": [
                    "AUDIO_ROUTE_VERSION",
                    "AudioProcessingError",
                    "AudioRouteConfig",
                    "AudioRouteSummary",
                    "MediaProbe",
                    "TranscriptResult",
                    "TranscriptSegment",
                    "WhisperRuntime",
                    "WhisperRuntimeError",
                ],
                "warning_policy": "silent",
            },
            {
                "role": "probe",
                "canonical_module_id": "neocortex.capabilities.formats.audio.probe",
                "public_symbols": ["MAX_FFPROBE_OUTPUT_BYTES", "probe_media", "resolve_ffprobe"],
                "warning_policy": "silent",
            },
            {
                "role": "route",
                "canonical_module_id": "neocortex.capabilities.formats.audio.route",
                "public_symbols": ["AUDIO_MIME_TYPES", "AudioRoute", "search_audio_state"],
                "warning_policy": "silent",
            },
            {
                "role": "state",
                "canonical_module_id": "neocortex.capabilities.formats.audio.state",
                "public_symbols": [
                    "AUDIO_SCHEMA_VERSION",
                    "audio_database",
                    "initialize_audio_state",
                ],
                "warning_policy": "silent",
            },
            {
                "role": "whisper",
                "canonical_module_id": "neocortex.capabilities.formats.audio.whisper",
                "public_symbols": [
                    "WhisperTranscriber",
                    "audio_runtime_doctor",
                    "resolve_whisper_runtime",
                ],
                "warning_policy": "silent",
            },
        ],
        "route": {
            "route_name": "audio",
            "input_source": "route_candidates",
            "subject_match_kind": "mime_prefix",
            "subject_value": "audio/",
            "route_class": {
                "module_id": "neocortex.capabilities.formats.audio.route",
                "symbol_name": "AudioRoute",
            },
            "config_class": {
                "module_id": "neocortex.capabilities.formats.audio.models",
                "symbol_name": "AudioRouteConfig",
            },
            "summary_class": {
                "module_id": "neocortex.capabilities.formats.audio.models",
                "symbol_name": "AudioRouteSummary",
            },
            "version_symbol": {
                "module_id": "neocortex.capabilities.formats.audio.models",
                "symbol_name": "AUDIO_ROUTE_VERSION",
            },
        },
        "state": {
            "state_owner_id": "audio",
            "state_store_id": "sqlite:audio.sqlite3",
            "database_name": "audio.sqlite3",
            "knowledge_path_attribute": "audio",
            "expected_schema_version": 2,
            "knowledge_read_kind": "documents",
            "knowledge_capture_mode": "configured",
            "state_module_id": "neocortex.capabilities.formats.audio.state",
            "schema_module_id": "neocortex.capabilities.formats.audio.state",
            "schema_version_symbol": {
                "module_id": "neocortex.capabilities.formats.audio.state",
                "symbol_name": "AUDIO_SCHEMA_VERSION",
            },
            "storage_engine": "sqlite",
        },
        "test_roots": [
            "tests/test_audio_probe_bounded.py",
            "tests/test_audio_route.py",
            "tests/test_capability_registry.py",
            "tests/test_cli_audio_surface.py",
            "tests/test_route_schema_contracts.py",
        ],
        "executable_module_ids": [],
    },
    {
        "capability_id": "docx",
        "architecture_family_id": "neocortex.capabilities.formats",
        "logical_owner_id": "docx",
        "canonical_module_tree": "neocortex.capabilities.formats.docx",
        "modules": [
            {
                "role": "integrity",
                "canonical_module_id": "neocortex.capabilities.formats.docx.integrity",
                "public_symbols": [],
                "warning_policy": "silent",
            },
            {
                "role": "layout",
                "canonical_module_id": "neocortex.capabilities.formats.docx.layout",
                "public_symbols": [],
                "warning_policy": "silent",
            },
            {
                "role": "models",
                "canonical_module_id": "neocortex.capabilities.formats.docx.models",
                "public_symbols": ["ALGORITHM_VERSION", "DocxRouteConfig", "DocxRouteSummary"],
                "warning_policy": "silent",
            },
            {
                "role": "route",
                "canonical_module_id": "neocortex.capabilities.formats.docx.route",
                "public_symbols": ["DOCX_MIME", "DocxRoute", "DocxRouteConfig", "DocxRouteSummary"],
                "warning_policy": "silent",
            },
            {
                "role": "schema",
                "canonical_module_id": "neocortex.capabilities.formats.docx.schema",
                "public_symbols": [
                    "DOCX_SCHEMA_VERSION",
                    "validate_docx_metadata",
                    "validate_docx_schema",
                ],
                "warning_policy": "silent",
            },
            {
                "role": "state",
                "canonical_module_id": "neocortex.capabilities.formats.docx.state",
                "public_symbols": ["connect_docx_state", "docx_database", "initialize_docx_state"],
                "warning_policy": "silent",
            },
        ],
        "route": {
            "route_name": "docx",
            "input_source": "route_candidates",
            "subject_match_kind": "exact_mime",
            "subject_value": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
            "route_class": {
                "module_id": "neocortex.capabilities.formats.docx.route",
                "symbol_name": "DocxRoute",
            },
            "config_class": {
                "module_id": "neocortex.capabilities.formats.docx.route",
                "symbol_name": "DocxRouteConfig",
            },
            "summary_class": {
                "module_id": "neocortex.capabilities.formats.docx.route",
                "symbol_name": "DocxRouteSummary",
            },
            "version_symbol": {
                "module_id": "neocortex.capabilities.formats.docx.models",
                "symbol_name": "ALGORITHM_VERSION",
            },
        },
        "state": {
            "state_owner_id": "docx",
            "state_store_id": "sqlite:docx.sqlite3",
            "database_name": "docx.sqlite3",
            "knowledge_path_attribute": "docx",
            "expected_schema_version": 6,
            "knowledge_read_kind": "documents",
            "knowledge_capture_mode": "configured",
            "state_module_id": "neocortex.capabilities.formats.docx.state",
            "schema_module_id": "neocortex.capabilities.formats.docx.schema",
            "schema_version_symbol": {
                "module_id": "neocortex.capabilities.formats.docx.schema",
                "symbol_name": "DOCX_SCHEMA_VERSION",
            },
            "storage_engine": "sqlite",
        },
        "test_roots": [
            "tests/test_capability_registry.py",
            "tests/test_docx_route.py",
            "tests/test_pdf_docx_schema_contracts.py",
        ],
        "executable_module_ids": [],
    },
    {
        "capability_id": "image",
        "architecture_family_id": "neocortex.capabilities.formats",
        "logical_owner_id": "image",
        "canonical_module_tree": "neocortex.capabilities.formats.image",
        "modules": [
            {
                "role": "analysis",
                "canonical_module_id": "neocortex.capabilities.formats.image.analysis",
                "public_symbols": [],
                "warning_policy": "silent",
            },
            {
                "role": "decision",
                "canonical_module_id": "neocortex.capabilities.formats.image.decision",
                "public_symbols": [],
                "warning_policy": "silent",
            },
            {
                "role": "decode",
                "canonical_module_id": "neocortex.capabilities.formats.image.decode",
                "public_symbols": [],
                "warning_policy": "silent",
            },
            {
                "role": "document",
                "canonical_module_id": "neocortex.capabilities.formats.image.document",
                "public_symbols": [],
                "warning_policy": "silent",
            },
            {
                "role": "errors",
                "canonical_module_id": "neocortex.capabilities.formats.image.errors",
                "public_symbols": [],
                "warning_policy": "silent",
            },
            {
                "role": "features",
                "canonical_module_id": "neocortex.capabilities.formats.image.features",
                "public_symbols": [],
                "warning_policy": "silent",
            },
            {
                "role": "isolation",
                "canonical_module_id": "neocortex.capabilities.formats.image.isolation",
                "public_symbols": [],
                "warning_policy": "silent",
            },
            {
                "role": "models",
                "canonical_module_id": "neocortex.capabilities.formats.image.models",
                "public_symbols": [],
                "warning_policy": "silent",
            },
            {
                "role": "png",
                "canonical_module_id": "neocortex.capabilities.formats.image.png",
                "public_symbols": [],
                "warning_policy": "silent",
            },
            {
                "role": "policy",
                "canonical_module_id": "neocortex.capabilities.formats.image.policy",
                "public_symbols": [],
                "warning_policy": "silent",
            },
            {
                "role": "route",
                "canonical_module_id": "neocortex.capabilities.formats.image.route",
                "public_symbols": [
                    "IMAGE_ROUTE_VERSION",
                    "ImageRoute",
                    "ImageRouteConfig",
                    "ImageRouteSummary",
                ],
                "warning_policy": "silent",
            },
            {
                "role": "semantics",
                "canonical_module_id": "neocortex.capabilities.formats.image.semantics",
                "public_symbols": [],
                "warning_policy": "silent",
            },
            {
                "role": "state",
                "canonical_module_id": "neocortex.capabilities.formats.image.state",
                "public_symbols": [
                    "SCHEMA_VERSION",
                    "connect_image_state",
                    "image_database",
                    "initialize_image_state",
                ],
                "warning_policy": "silent",
            },
            {
                "role": "visual",
                "canonical_module_id": "neocortex.capabilities.formats.image.visual",
                "public_symbols": [],
                "warning_policy": "silent",
            },
        ],
        "route": {
            "route_name": "image",
            "input_source": "route_candidates",
            "subject_match_kind": "mime_prefix",
            "subject_value": "image/",
            "route_class": {
                "module_id": "neocortex.capabilities.formats.image.route",
                "symbol_name": "ImageRoute",
            },
            "config_class": {
                "module_id": "neocortex.capabilities.formats.image.route",
                "symbol_name": "ImageRouteConfig",
            },
            "summary_class": {
                "module_id": "neocortex.capabilities.formats.image.route",
                "symbol_name": "ImageRouteSummary",
            },
            "version_symbol": {
                "module_id": "neocortex.capabilities.formats.image.route",
                "symbol_name": "IMAGE_ROUTE_VERSION",
            },
        },
        "state": {
            "state_owner_id": "image",
            "state_store_id": "sqlite:image.sqlite3",
            "database_name": "image.sqlite3",
            "knowledge_path_attribute": "image",
            "expected_schema_version": 6,
            "knowledge_read_kind": "images",
            "knowledge_capture_mode": "configured",
            "state_module_id": "neocortex.capabilities.formats.image.state",
            "schema_module_id": "neocortex.capabilities.formats.image.state",
            "schema_version_symbol": {
                "module_id": "neocortex.capabilities.formats.image.state",
                "symbol_name": "SCHEMA_VERSION",
            },
            "storage_engine": "sqlite",
        },
        "test_roots": [
            "tests/test_capability_registry.py",
            "tests/test_image_analysis.py",
            "tests/test_image_classifier_memory.py",
            "tests/test_image_document.py",
            "tests/test_image_features.py",
            "tests/test_image_isolation.py",
            "tests/test_image_ocr_profiles.py",
            "tests/test_image_png.py",
            "tests/test_image_route.py",
            "tests/test_image_schema_contract.py",
            "tests/test_image_semantics.py",
        ],
        "executable_module_ids": [],
    },
    {
        "capability_id": "office",
        "architecture_family_id": "neocortex.capabilities.formats",
        "logical_owner_id": "office",
        "canonical_module_tree": "neocortex.capabilities.formats.office",
        "modules": [
            {
                "role": "extraction",
                "canonical_module_id": "neocortex.capabilities.formats.office.extraction",
                "public_symbols": ["extract_office_document"],
                "warning_policy": "silent",
            },
            {
                "role": "extraction_support",
                "canonical_module_id": "neocortex.capabilities.formats.office.extraction_support",
                "public_symbols": [],
                "warning_policy": "silent",
            },
            {
                "role": "legacy_worker",
                "canonical_module_id": "neocortex.capabilities.formats.office.legacy_worker",
                "public_symbols": ["main"],
                "warning_policy": "silent",
            },
            {
                "role": "models",
                "canonical_module_id": "neocortex.capabilities.formats.office.models",
                "public_symbols": [
                    "ExtractedOfficeDocument",
                    "OFFICE_MIME_FORMATS",
                    "OFFICE_ROUTE_VERSION",
                    "OfficeExtractionError",
                    "OfficeRouteConfig",
                    "OfficeRouteSummary",
                    "XlsxCell",
                ],
                "warning_policy": "silent",
            },
            {
                "role": "route",
                "canonical_module_id": "neocortex.capabilities.formats.office.route",
                "public_symbols": [
                    "OFFICE_MIME_FORMATS",
                    "OFFICE_ROUTE_VERSION",
                    "OfficeRoute",
                    "OfficeRouteConfig",
                    "OfficeRouteSummary",
                    "search_office_state",
                ],
                "warning_policy": "silent",
            },
            {
                "role": "state",
                "canonical_module_id": "neocortex.capabilities.formats.office.state",
                "public_symbols": [
                    "OFFICE_SCHEMA_VERSION",
                    "initialize_office_state",
                    "office_database",
                    "search_office_state",
                ],
                "warning_policy": "silent",
            },
            {
                "role": "xlsx",
                "canonical_module_id": "neocortex.capabilities.formats.office.xlsx",
                "public_symbols": [],
                "warning_policy": "silent",
            },
        ],
        "route": {
            "route_name": "office",
            "input_source": "route_candidates",
            "subject_match_kind": "exact_mime",
            "subject_value": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
            "route_class": {
                "module_id": "neocortex.capabilities.formats.office.route",
                "symbol_name": "OfficeRoute",
            },
            "config_class": {
                "module_id": "neocortex.capabilities.formats.office.models",
                "symbol_name": "OfficeRouteConfig",
            },
            "summary_class": {
                "module_id": "neocortex.capabilities.formats.office.models",
                "symbol_name": "OfficeRouteSummary",
            },
            "version_symbol": {
                "module_id": "neocortex.capabilities.formats.office.models",
                "symbol_name": "OFFICE_ROUTE_VERSION",
            },
        },
        "state": {
            "state_owner_id": "office",
            "state_store_id": "sqlite:office.sqlite3",
            "database_name": "office.sqlite3",
            "knowledge_path_attribute": "office",
            "expected_schema_version": 3,
            "knowledge_read_kind": "documents",
            "knowledge_capture_mode": "configured",
            "state_module_id": "neocortex.capabilities.formats.office.state",
            "schema_module_id": "neocortex.capabilities.formats.office.state",
            "schema_version_symbol": {
                "module_id": "neocortex.capabilities.formats.office.state",
                "symbol_name": "OFFICE_SCHEMA_VERSION",
            },
            "storage_engine": "sqlite",
        },
        "test_roots": [
            "tests/test_application_config_media_projections.py",
            "tests/test_capability_registry.py",
            "tests/test_cli_review_office.py",
            "tests/test_office_route.py",
            "tests/test_route_schema_contracts.py",
            "tests/test_text_derivation_route.py",
            "tests/test_text_implementation_identity.py",
        ],
        "executable_module_ids": ["neocortex.capabilities.formats.office.legacy_worker"],
    },
    {
        "capability_id": "video",
        "architecture_family_id": "neocortex.capabilities.formats",
        "logical_owner_id": "video",
        "canonical_module_tree": "neocortex.capabilities.formats.video",
        "modules": [
            {
                "role": "frames",
                "canonical_module_id": "neocortex.capabilities.formats.video.frames",
                "public_symbols": [
                    "ExtractedVideoFrame",
                    "MAX_VIDEO_FRAMES",
                    "VideoFrameBatch",
                    "VideoFrameSamplingConfig",
                    "build_frame_plan",
                    "resolve_video_ffmpeg",
                    "sampled_video_frames",
                ],
                "warning_policy": "silent",
            },
            {
                "role": "models",
                "canonical_module_id": "neocortex.capabilities.formats.video.models",
                "public_symbols": [
                    "SubtitleStreamProbe",
                    "VIDEO_ROUTE_VERSION",
                    "VideoMediaProbe",
                    "VideoProcessingError",
                    "VideoRouteSummary",
                    "VideoStreamProbe",
                ],
                "warning_policy": "silent",
            },
            {
                "role": "probe",
                "canonical_module_id": "neocortex.capabilities.formats.video.probe",
                "public_symbols": ["decode_video_probe", "probe_video", "resolve_video_ffprobe"],
                "warning_policy": "silent",
            },
            {
                "role": "route",
                "canonical_module_id": "neocortex.capabilities.formats.video.route",
                "public_symbols": [
                    "VIDEO_MIME_TYPES",
                    "VideoRoute",
                    "VideoRouteConfig",
                    "search_video_state",
                ],
                "warning_policy": "silent",
            },
            {
                "role": "state",
                "canonical_module_id": "neocortex.capabilities.formats.video.state",
                "public_symbols": [
                    "VIDEO_SCHEMA_VERSION",
                    "initialize_video_state",
                    "search_video_state",
                    "validate_video_schema",
                    "video_database",
                    "video_state_status",
                ],
                "warning_policy": "silent",
            },
        ],
        "route": {
            "route_name": "video",
            "input_source": "route_candidates",
            "subject_match_kind": "mime_prefix",
            "subject_value": "video/",
            "route_class": {
                "module_id": "neocortex.capabilities.formats.video.route",
                "symbol_name": "VideoRoute",
            },
            "config_class": {
                "module_id": "neocortex.capabilities.formats.video.route",
                "symbol_name": "VideoRouteConfig",
            },
            "summary_class": {
                "module_id": "neocortex.capabilities.formats.video.models",
                "symbol_name": "VideoRouteSummary",
            },
            "version_symbol": {
                "module_id": "neocortex.capabilities.formats.video.models",
                "symbol_name": "VIDEO_ROUTE_VERSION",
            },
        },
        "state": {
            "state_owner_id": "video",
            "state_store_id": "sqlite:video.sqlite3",
            "database_name": "video.sqlite3",
            "knowledge_path_attribute": "video",
            "expected_schema_version": 2,
            "knowledge_read_kind": "videos",
            "knowledge_capture_mode": "configured",
            "state_module_id": "neocortex.capabilities.formats.video.state",
            "schema_module_id": "neocortex.capabilities.formats.video.state",
            "schema_version_symbol": {
                "module_id": "neocortex.capabilities.formats.video.state",
                "symbol_name": "VIDEO_SCHEMA_VERSION",
            },
            "storage_engine": "sqlite",
        },
        "test_roots": [
            "tests/test_capability_registry.py",
            "tests/test_cli_video_surface.py",
            "tests/test_route_schema_contracts.py",
            "tests/test_video_content_types.py",
            "tests/test_video_frames.py",
            "tests/test_video_knowledge_integration.py",
            "tests/test_video_probe.py",
            "tests/test_video_route.py",
            "tests/test_video_state.py",
        ],
        "executable_module_ids": [],
    },
)

__all__ = ["CAPABILITY_SPEC_PAYLOADS"]
